name: Daily Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  count_commits_and_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages  

      - name: Obtenir Commits dels usuaris
        id: get_contributors
        run: |
          cd docs
          python daily_metrics.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Committing results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/daily_metrics.json
          git commit -m "Actualitzar daily_metrics.json" || exit 0
          git push
